#!/usr/bin/env sh
# Gradle wrapper script (minimal). Generated by automated helper.
set -e
DIRNAME="$(cd "$(dirname "$0")" && pwd)"
APP_BASE_NAME="`basename "$0"`"
# Find java
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi
# Classpath to wrapper jar
CLASSPATH="$DIRNAME/gradle/wrapper/gradle-wrapper.jar"
exec "$JAVACMD" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

