input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index_name]" => "banking-logs-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "banking-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}

